//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Uhanov.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int IdClient { get; set; }
        public string LastNameClient { get; set; }
        public string FirstNameClient { get; set; }
        public string MiddleNameClient { get; set; }
        public string NameCompany { get; set; }
        public string PhoneNumberClient { get; set; }
        public string EmailClient { get; set; }
        public Nullable<int> IdOrder { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
